"use client";
import { Lato } from "next/font/google";
import "../app/globals.css";
import { useEffect, useState } from "react";
import close from "@/images/closeIcon.svg";
import Image from "next/image";
import PopupHomePage from "@/components/Popup/page";
import Refresh from "@/components/Refresh/page";
import "../components/home/homeParallax.css";
import "../application_pages/homePage/homepage.css";
const lato = Lato({
  weight: ["100", "300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
});

// export const metadata = {
//   title: 'Royale touche',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [popup, setPopup] = useState(false);
  useEffect(() => {
    setTimeout(() => {
      setPopup(true);
    }, 20000);
  }, []);
  useEffect(() => {
    const handleScroll = () => {
      if (popup) {
        document.body.style.overflow = "hidden";
      } else {
        document.body.style.overflow = "";
      }
    };

    // Call the function to handle scrolling
    handleScroll();

    // Clean up effect on component unmount
    return () => {
      document.body.style.overflow = ""; // Reset the overflow style
    };
  }, [popup]); // Depend on the popup state
  const handlePopup = () => {
    setPopup(false);
  };

  useEffect(() => {
    console.log(window);
    window.dataLayer = window.dataLayer || [];
    function gtag() {
      dataLayer.push(arguments);
    }
    gtag("js", new Date());

    gtag("config", "G-MTKLKTNEJT");

    (function (w, d, s, l, i) {
      w[l] = w[l] || [];
      w[l].push({ "gtm.start": new Date().getTime(), event: "gtm.js" });
      var f = d.getElementsByTagName(s)[0],
        j = d.createElement(s),
        dl = l != "dataLayer" ? "&l=" + l : "";
      j.async = true;
      j.src = "https://www.googletagmanager.com/gtm.js?id=" + i + dl;
      f.parentNode.insertBefore(j, f);
    })(window, document, "script", "dataLayer", "GTM-W6VNSPT6");
  });

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "Royale Touche Plywood",
    url: "https://plywood.royaletouche.com/",
    logo: "https://plywood.royaletouche.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FfinalNavbarLogo.f0efe1b4.png&w=256&q=75",
  };

  const jsonLd2 = {
    "@context": "https://schema.org/",
    "@type": "WebSite",
    name: "Royale Touche Plywood",
    url: "https://plywood.royaletouche.com/",
    potentialAction: {
      "@type": "SearchAction",
      target: "{search_term_string}",
      "query-input": "required name=search_term_string",
    },
  };
  return (
    <html lang="en">
      <head>
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-MTKLKTNEJT"
        ></script>
        <link rel="canonical" href="https://plywood.royaletouche.com/" />
      </head>

      <body className={lato.className}>
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-W6VNSPT6"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        ></script>

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd2) }}
        ></script>
        <div className={`${popup ? "demo" : ""}`}>
          {popup && (
            <div className="popup">
              <div className="popup_wrapper">
                <PopupHomePage />
                <div className="close" onClick={handlePopup}>
                  <Image src={close} alt="close" />
                </div>
              </div>
            </div>
          )}
        </div>
        <Refresh/>
        {children}
      </body>
    </html>
  );
}
